/**
 * applicationAgent.js
 * Fills and submits LinkedIn Easy Apply forms.
 * Handles multi-step modals, file uploads, and screening questions.
 * Screening answers are generated by Claude AI inline.
 */

import { AgentBase } from '../core/agentBase.js';
import { browserPool } from '../core/browserPool.js';
import { JobScoutAgent } from './jobScoutAgent.js';
import { humanClick, humanType, humanTypeAndClear, randomDelay, readingPause, thinkingPause, microPause } from '../utils/humanize.js';
import { readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const userProfile = JSON.parse(readFileSync(join(__dirname, '../../config/user-profile.json'), 'utf8'));

const SCREENING_SYSTEM_PROMPT = `You are a job applicant's assistant, answering screening questions concisely and honestly based on their profile. Keep answers brief: 1-2 sentences for yes/no questions, 2-3 for open-ended. For numeric fields give realistic numbers. Always present the candidate in the best honest light.`;

export class ApplicationAgent extends AgentBase {
  constructor() {
    super(
      'ApplicationAgent',
      'Submits LinkedIn Easy Apply forms, uploads resume/cover letter, answers screening questions with Claude AI',
      SCREENING_SYSTEM_PROMPT
    );
  }

  /**
   * @param {{ job, resumePdfPath, coverLetterText, coverLetterPdfPath }} input
   * @returns {boolean} applied
   */
  async onRun({ job, resumePdfPath, coverLetterText, coverLetterPdfPath }) {
    if (process.env.AUTO_APPLY !== 'true') {
      this._log(`DRY RUN — would apply to: ${job.title} @ ${job.company}`);
      return false;
    }

    if (!job.hasEasyApply) {
      this._log(`No Easy Apply for ${job.title} @ ${job.company} — skipping.`, 'warn');
      return false;
    }

    this._log(`Starting Easy Apply: ${job.title} @ ${job.company}`);
    const page = await browserPool.getPage();

    try {
      // Navigate to job page
      if (!page.url().includes(job.jobId)) {
        await page.goto(job.url, { waitUntil: 'domcontentloaded', timeout: 30_000 });
        await thinkingPause();
      }

      // Click Easy Apply
      const easyApplyBtn = page.locator('button.jobs-apply-button, .artdeco-button--primary')
        .filter({ hasText: /easy apply/i }).first();
      await easyApplyBtn.waitFor({ state: 'visible', timeout: 10_000 });
      await humanClick(page, easyApplyBtn);
      await randomDelay(1500, 3000);

      const submitted = await this._handleModal(page, job, resumePdfPath, coverLetterText, coverLetterPdfPath);

      if (submitted) {
        JobScoutAgent.recordApplied(job);
        this._publish('job:applied', { jobId: job.jobId, title: job.title, company: job.company });
        this._log(`Successfully applied to: ${job.title} @ ${job.company}`);
      }

      return submitted;

    } catch (err) {
      this._log(`Apply failed: ${err.message}`, 'error');
      await page.keyboard.press('Escape').catch(() => {});
      return false;
    }
  }

  // ── Modal loop ─────────────────────────────────────────────────────────────
  async _handleModal(page, job, resumePdfPath, coverLetterText, coverLetterPdfPath) {
    for (let step = 0; step < 10; step++) {
      await readingPause();

      const modalOpen = await page.locator('.jobs-easy-apply-modal').isVisible().catch(() => false);
      if (!modalOpen) break;

      if (await this._isSuccess(page)) {
        await this._closeModal(page);
        return true;
      }

      await this._fillStep(page, job, resumePdfPath, coverLetterText, coverLetterPdfPath);
      await readingPause();

      if (await this._isReviewStep(page)) {
        const submitBtn = page.locator('button').filter({ hasText: /submit application/i }).first();
        if (await submitBtn.isVisible().catch(() => false)) {
          this._log('Clicking Submit Application...');
          await humanClick(page, submitBtn);
          await randomDelay(2000, 4000);
          await this._closeModal(page);
          return await this._isSuccess(page);
        }
      }

      // Next / Review
      const reviewBtn = page.locator('button').filter({ hasText: /^review$/i }).first();
      const nextBtn = page.locator('button').filter({ hasText: /^next$/i }).first();

      if (await reviewBtn.isVisible().catch(() => false)) {
        await humanClick(page, reviewBtn);
      } else if (await nextBtn.isVisible().catch(() => false)) {
        await humanClick(page, nextBtn);
      } else {
        this._log('No next/review button — breaking out of modal.', 'warn');
        break;
      }

      await randomDelay(1500, 3000);
    }
    return false;
  }

  // ── Fill one modal step ────────────────────────────────────────────────────
  async _fillStep(page, job, resumePdfPath, coverLetterText, coverLetterPdfPath) {
    await this._uploadResume(page, resumePdfPath);
    await this._fillCoverLetter(page, coverLetterText, coverLetterPdfPath);
    await this._answerScreeningQuestions(page, job);
  }

  async _uploadResume(page, path) {
    const input = page.locator('input[type="file"][name*="resume"], input[type="file"][accept*="pdf"]').first();
    if (await input.count() > 0) {
      await input.setInputFiles(path).catch(e => this._log(`Resume upload failed: ${e.message}`, 'warn'));
      await randomDelay(800, 1500);
    }
  }

  async _fillCoverLetter(page, text, pdfPath) {
    const area = page.locator('textarea[id*="cover"], textarea[placeholder*="cover"]').first();
    if (await area.count() > 0 && await area.isVisible().catch(() => false)) {
      await humanTypeAndClear(area, text);
      return;
    }
    if (pdfPath) {
      const fileInput = page.locator('input[type="file"][name*="cover"]').first();
      if (await fileInput.count() > 0) await fileInput.setInputFiles(pdfPath).catch(() => {});
    }
  }

  async _answerScreeningQuestions(page, job) {
    const groups = await page.locator('.jobs-easy-apply-form-section__grouping, .fb-form-element').all();
    const pending = [];

    for (const group of groups) {
      const label = await group.locator('label, legend, .fb-form-element__label').first()
        .textContent({ timeout: 2000 }).then(t => t?.trim()).catch(() => null);
      if (!label) continue;

      const input = group.locator('input:not([type="file"]), textarea, select').first();
      if (await input.count() === 0) continue;

      const val = await input.inputValue().catch(() => '');
      if (val?.length > 0) continue;

      pending.push({ label, input });
    }

    if (pending.length === 0) return;

    this._log(`Answering ${pending.length} screening question(s) with Claude AI...`);

    const questions = pending.map(p => p.label);
    const answers = await this._generateAnswers(questions, job);

    for (let i = 0; i < pending.length; i++) {
      const { input } = pending[i];
      const answer = answers[i] || '';
      if (!answer) continue;
      try {
        const tag = await input.evaluate(el => el.tagName.toLowerCase());
        if (tag === 'select') {
          await input.selectOption({ label: answer }).catch(() => input.selectOption({ index: 1 }));
        } else {
          await humanTypeAndClear(input, answer);
        }
        await microPause();
      } catch (err) {
        this._log(`Could not fill Q "${questions[i]?.slice(0, 40)}": ${err.message}`, 'warn');
      }
    }
  }

  async _generateAnswers(questions, job) {
    const prompt = `Answer these job application screening questions for the candidate.

CANDIDATE: ${userProfile.applicant.name}, ${userProfile.applicant.currentRole}, ${userProfile.applicant.yearsOfExperience} years experience.
JOB: ${job.title} at ${job.company}
WORK AUTH: ${userProfile.applicant.workAuthorization}
SALARY EXPECTATION: ${userProfile.applicant.salaryExpectation}

QUESTIONS:
${questions.map((q, i) => `${i + 1}. ${q}`).join('\n')}

Reply with a JSON array of answer strings, one per question. Only the array — no other text.`;

    const raw = await this._think(prompt, 1000);
    try {
      return JSON.parse(raw.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim());
    } catch {
      return questions.map(() => '');
    }
  }

  // ── Modal helpers ──────────────────────────────────────────────────────────
  async _isReviewStep(page) {
    const header = await page.locator('.jobs-easy-apply-modal h3, .t-bold').first()
      .textContent({ timeout: 2000 }).then(t => t?.toLowerCase() ?? '').catch(() => '');
    return header.includes('review') || header.includes('additional questions');
  }

  async _isSuccess(page) {
    return page.locator('.artdeco-inline-feedback--success, .t-green, [data-test-modal=""]')
      .filter({ hasText: /submitted|applied|successfully/i })
      .first().isVisible({ timeout: 2000 }).catch(() => false);
  }

  async _closeModal(page) {
    const btn = page.locator('button[aria-label="Dismiss"], button[data-test-modal-close-btn]').first();
    if (await btn.isVisible({ timeout: 2000 }).catch(() => false)) {
      await humanClick(page, btn);
    } else {
      await page.keyboard.press('Escape').catch(() => {});
    }
    await randomDelay(800, 1500);
  }
}
